### ISSUE TITLE
Converting distances to anomaly scores between 0 and 1.

### ISSUE THREAD

**Issue by rishabh-akridata** [Pangoraw/PaDiM#12]
Hi @Pangoraw,
How can we convert the distances to anomaly scores between 0 and 1, where 1 is for the anomalous sample and 0 for non-anomalous? For example if this is the distance matrix ```tensor([[0.9866],
        [0.9866],
        [0.9869],
        ...,
        [1.3533],
        [1.3511],
        [1.3511]])``` we have of shape torch.Size([4096, 1]) for single image. How to convert these distances into a single anomaly score between 0 and 1.

Thanks

**Comment by Pangoraw** [comment]
it is not really straightforward, since what constitutes an anomalous sample depends on your data/requirements. This is why most testing methods use the ROC curve metric to not have to set a classification threshold.

Consider the following, you have a sample which as an anomaly score of 1, but then you later receive a sample which can be considered even more anomalous, what should be its score?

**Comment by rishabh-akridata** [comment]
Okay.
